DROP TABLE IF EXISTS FORNECEDOR;
DROP TABLE IF EXISTS REPARO;
DROP TABLE IF EXISTS JOGO;
DROP TABLE IF EXISTS EQUIP_CONSOLE;
DROP TABLE IF EXISTS EQUIP_COMPUTADOR;
DROP TABLE IF EXISTS EQUIPAMENTO;
DROP TABLE IF EXISTS FUNCIONARIO;
DROP TABLE IF EXISTS CLIENTE;

CREATE TABLE CLIENTE(
	cpf CHAR(11),
    rg CHAR(9),
    telefone CHAR(13),
    email VARCHAR(200),
    nome VARCHAR(100),
    PRIMARY KEY (cpf)
);

CREATE TABLE FUNCIONARIO(
	cpf CHAR(11),
    rg CHAR (9),
    salario DECIMAL(10,2),
	cargo VARCHAR(20),
    nome VARCHAR(100),
    PRIMARY KEY(cpf)
);

CREATE TABLE EQUIPAMENTO(
	id INTEGER,
	preco_h DECIMAL(10,2),
    status_disponibilidade VARCHAR(20),
	PRIMARY KEY (id)
);

CREATE TABLE EQUIP_COMPUTADOR(
	id_equip INTEGER,
	login VARCHAR(20),
    senha VARCHAR(8),
    sistema VARCHAR(30),
    PRIMARY KEY (id_equip),
    FOREIGN KEY (id_equip) REFERENCES EQUIPAMENTO(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE EQUIP_CONSOLE(
	id_equip INTEGER,
    qtde_controle INTEGER,
    PRIMARY KEY (id_equip),
    FOREIGN KEY (id_equip) REFERENCES EQUIPAMENTO(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE JOGO(
	id INTEGER,
    nome VARCHAR(100),
    data_instalação DATE,
    nome_produtora VARCHAR(100),
    PRIMARY KEY (id)
);

CREATE TABLE REPARO(
	codigo INTEGER,
    preco DECIMAL(10,2),
    tipo_equipamento VARCHAR(20),
    descricao VARCHAR(200),
    PRIMARY KEY (codigo)
);

CREATE TABLE FORNECEDOR(
	cnpj CHAR(14),
    nome_empresa VARCHAR(100),
    nome_fornecedor VARCHAR(100),
    PRIMARY KEY (cnpj)
);
